export async function seed(knex) {
  await knex('suggestions').insert([
    {
      name: 'Auckland Sky Tower',
      city_name: 'Auckland',
      category: 'place',
      description:
        'Auckland Sky Tower offers breathtaking views of the city and harbor.',
      rating: 4.2,
      address: 'Victoria Street West, Auckland, New Zealand',
      opening_hours: '10 AM - 8 PM',
      link: 'https://www.skycityauckland.co.nz/',
      price_range: '',
    },
    {
      name: 'Auckland War Memorial Museum',
      city_name: 'Auckland',
      category: 'place',
      description:
        'Explore the Auckland War Memorial Museum and its rich history.',
      rating: 4.5,
      address: 'The Auckland Domain, Parnell, Auckland',
      opening_hours: '9 AM - 5 PM',
      link: 'https://www.aucklandmuseum.com/',
      price_range: '',
    },
    {
      name: 'Piha Beach',
      city_name: 'Auckland',
      category: 'place',
      description:
        'Relax at the beautiful Piha Beach, known for its black sand and rugged beauty.',
      rating: 4.0,
      address: 'Piha, Auckland, New Zealand',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'Auckland Art Gallery Toi o Tāmaki',
      city_name: 'Auckland',
      category: 'place',
      description:
        'Visit the Auckland Art Gallery Toi o Tāmaki for a diverse range of artworks.',
      rating: 4.3,
      address: 'Corner Kitchener and Wellesley Streets, Auckland',
      opening_hours: '10 AM - 5 PM',
      link: 'https://www.aucklandartgallery.com/',
      price_range: '',
    },
    {
      name: 'Auckland Botanic Gardens',
      city_name: 'Auckland',
      category: 'place',
      description:
        'Wander through the lush Auckland Botanic Gardens for a peaceful escape.',
      rating: 4.1,
      address: '102 Hill Road, Manurewa, Auckland',
      opening_hours: '8 AM - 6 PM',
      link: 'https://www.aucklandbotanicgardens.co.nz/',
      price_range: '',
    },
    {
      name: 'The Sugar Club',
      city_name: 'Auckland',
      category: 'restaurant',
      description:
        'Savor exquisite seafood at The Sugar Club with panoramic views of the city.',
      rating: 4.8,
      address:
        'Level 53, Sky Tower, Corner of Federal and Victoria Streets, Auckland',
      opening_hours: '6 PM - 11 PM',
      link: 'https://www.skycityauckland.co.nz/restaurants/the-sugar-club/',
      price_range: '20-40',
    },
    {
      name: 'Depot Eatery',
      city_name: 'Auckland',
      category: 'restaurant',
      description:
        'Indulge in authentic Kiwi cuisine at Depot Eatery in Auckland CBD.',
      rating: 4.6,
      address: '86 Federal St, Auckland',
      opening_hours: '7 AM - 11 PM',
      link: 'https://www.eatatdepot.co.nz/',
      price_range: '15-35',
    },
    {
      name: 'The Grove',
      city_name: 'Auckland',
      category: 'restaurant',
      description:
        'Experience fine dining at The Grove, known for its innovative New Zealand cuisine.',
      rating: 4.9,
      address: 'St Patricks Square, Wyndham Street, Auckland',
      opening_hours: '6 PM - 10 PM',
      link: 'https://thegroverestaurant.co.nz/',
      price_range: '25-40',
    },
    {
      name: 'Ortolana',
      city_name: 'Auckland',
      category: 'restaurant',
      description:
        'Enjoy a casual meal at Ortolana, offering fresh and seasonal produce.',
      rating: 4.5,
      address: '33 Tyler St, Britomart, Auckland',
      opening_hours: '8 AM - 10 PM',
      link: 'https://www.ortolana.co.nz/',
      price_range: '15-30',
    },
    {
      name: 'Azabu',
      city_name: 'Auckland',
      category: 'restaurant',
      description:
        'Discover the flavors of Japanese cuisine at Azabu in Ponsonby.',
      rating: 4.4,
      address: '26 Ponsonby Road, Auckland',
      opening_hours: '12 PM - 11 PM',
      link: 'https://azabu.co.nz/',
      price_range: '30-50',
    },
    {
      name: 'Cordis, Auckland',
      city_name: 'Auckland',
      category: 'hotel',
      description:
        'Experience luxury at the Cordis, Auckland with elegant rooms and exceptional service.',
      rating: 4.7,
      address: '83 Symonds Street, Grafton, Auckland',
      opening_hours: '',
      link: 'https://www.cordishotels.com/auckland/',
      price_range: '150-300',
    },
    {
      name: 'SO/ Auckland',
      city_name: 'Auckland',
      category: 'hotel',
      description:
        'Stay in style at the SO/ Auckland, a trendy hotel in the heart of the city.',
      rating: 4.6,
      address: '67 Customs Street East, Auckland',
      opening_hours: '',
      link: 'https://www.so-auckland.com/',
      price_range: '120-250',
    },
    {
      name: 'Hilton Auckland',
      city_name: 'Auckland',
      category: 'hotel',
      description:
        'Enjoy waterfront views at the Hilton Auckland, offering a luxurious stay.',
      rating: 4.8,
      address: 'Princes Wharf 147 Quay Street, Auckland',
      opening_hours: '',
      link: 'https://www3.hilton.com/en/hotels/new-zealand/hilton-auckland-AKLHIHI/index.html',
      price_range: '180-350',
    },
    {
      name: 'Grand Millennium Auckland',
      city_name: 'Auckland',
      category: 'hotel',
      description:
        'Experience modern comfort at the Grand Millennium Auckland in the city center.',
      rating: 4.5,
      address: '71 Mayoral Drive, Auckland',
      opening_hours: '',
      link: 'https://www.millenniumhotels.com/en/auckland/grand-millennium-auckland/',
      price_range: '130-270',
    },
    {
      name: 'SKYCITY Hotel',
      city_name: 'Auckland',
      category: 'hotel',
      description:
        'Relax at the SKYCITY Hotel, conveniently located near entertainment and dining options.',
      rating: 4.4,
      address: 'Corner Victoria and Federal Streets, Auckland',
      opening_hours: '',
      link: 'https://www.skycityauckland.co.nz/hotels/skycity-hotel/',
      price_range: '100-220',
    },
    {
      name: 'Tokyo Tower',
      city_name: 'Tokyo',
      category: 'place',
      description:
        'Visit the iconic Tokyo Tower for panoramic views of the cityscape.',
      rating: 4.6,
      address: '4 Chome-2-8 Shibakoen, Minato City, Tokyo 105-0011, Japan',
      opening_hours: '9 AM - 11 PM',
      link: 'https://www.tokyotower.co.jp/',
      price_range: '',
    },
    {
      name: 'Senso-ji Temple',
      city_name: 'Tokyo',
      category: 'place',
      description: 'Explore the historic Senso-ji Temple in Asakusa, Tokyo.',
      rating: 4.7,
      address: '2 Chome-3-1 Asakusa, Taito City, Tokyo 111-0032, Japan',
      opening_hours: '6 AM - 5 PM',
      link: 'https://www.senso-ji.jp/',
      price_range: '',
    },
    {
      name: 'teamLab Borderless',
      city_name: 'Tokyo',
      category: 'place',
      description:
        'Experience modern art at the teamLab Borderless digital art museum.',
      rating: 4.9,
      address: '1 Chome-3-8 Aomi, Koto City, Tokyo 135-0064, Japan',
      opening_hours: '10 AM - 7 PM',
      link: 'https://www.teamlab.art/',
      price_range: '',
    },
    {
      name: 'Ueno Park',
      city_name: 'Tokyo',
      category: 'place',
      description:
        'Stroll through Ueno Park and enjoy cherry blossoms during the spring season.',
      rating: 4.5,
      address: 'Uenokoen, Taito City, Tokyo 110-0007, Japan',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'Tsukiji Fish Market',
      city_name: 'Tokyo',
      category: 'place',
      description:
        'Discover the lively atmosphere of the Tsukiji Fish Market for fresh seafood.',
      rating: 4.8,
      address: '5 Chome-2-1 Tsukiji, Chuo City, Tokyo 104-0045, Japan',
      opening_hours: '5 AM - 2 PM',
      link: 'https://www.tsukiji.or.jp/',
      price_range: '',
    },
    {
      name: 'Sukiyabashi Jiro',
      city_name: 'Tokyo',
      category: 'restaurant',
      description:
        'Indulge in traditional sushi at Sukiyabashi Jiro, a renowned Michelin-starred restaurant.',
      rating: 4.9,
      address: '4 Chome-2-15 Ginza, Chuo City, Tokyo 104-0061, Japan',
      opening_hours: '11:30 AM - 2 PM, 5:30 PM - 8 PM',
      link: '',
      price_range: '30-50',
    },
    {
      name: 'Ichiraku Ramen',
      city_name: 'Tokyo',
      category: 'restaurant',
      description:
        'Experience the flavors of ramen at Ichiraku Ramen in Akihabara.',
      rating: 4.5,
      address: '3 Chome-3-11 Sotokanda, Chiyoda City, Tokyo 101-0021, Japan',
      opening_hours: '11 AM - 9 PM',
      link: '',
      price_range: '10-20',
    },
    {
      name: 'Ukai-tei Omotesando',
      city_name: 'Tokyo',
      category: 'restaurant',
      description:
        'Enjoy teppanyaki at Ukai-tei Omotesando for a unique dining experience.',
      rating: 4.7,
      address: '4 Chome-4-13 Jingumae, Shibuya City, Tokyo 150-0001, Japan',
      opening_hours: '11:30 AM - 2 PM, 5 PM - 9:30 PM',
      link: 'https://www.ukai.co.jp/english/omotesando/',
      price_range: '40-70',
    },
    {
      name: 'Narisawa',
      city_name: 'Tokyo',
      category: 'restaurant',
      description:
        'Experience innovative Japanese cuisine at Narisawa, a two-star Michelin restaurant.',
      rating: 4.9,
      address: '2 Chome-6-15 Minamiaoyama, Minato City, Tokyo 107-0062, Japan',
      opening_hours: '12 PM - 1:30 PM, 6:30 PM - 8:30 PM',
      link: 'https://narisawa-yoshihiro.com/',
      price_range: '80-120',
    },
    {
      name: 'Ryugin',
      city_name: 'Tokyo',
      category: 'restaurant',
      description:
        'Savor kaiseki at Ryugin, a three-star Michelin restaurant in Roppongi.',
      rating: 4.8,
      address: '7 Chome-17-24 Roppongi, Minato City, Tokyo 106-0032, Japan',
      opening_hours: '6 PM - 10:30 PM',
      link: 'https://www.nihonryori-ryugin.com/',
      price_range: '50-80',
    },
    {
      name: 'Park Hyatt Tokyo',
      city_name: 'Tokyo',
      category: 'hotel',
      description:
        'Experience luxury at the Park Hyatt Tokyo with elegant rooms and stunning views.',
      rating: 4.9,
      address: '3-7-1-2 Nishi Shinjuku, Shinjuku City, Tokyo 163-1055, Japan',
      opening_hours: '',
      link: 'https://www.hyatt.com/en-US/hotel/japan/park-hyatt-tokyo/tyoph',
      price_range: '250-500',
    },
    {
      name: 'Aman Tokyo',
      city_name: 'Tokyo',
      category: 'hotel',
      description:
        'Stay in tranquility at Aman Tokyo, a luxury hotel blending traditional and modern design.',
      rating: 4.8,
      address: '1-5-6 Otemachi, Chiyoda City, Tokyo 100-0004, Japan',
      opening_hours: '',
      link: 'https://www.aman.com/tokyo',
      price_range: '300-600',
    },
    {
      name: 'Mandarin Oriental, Tokyo',
      city_name: 'Tokyo',
      category: 'hotel',
      description:
        'Enjoy sophistication at the Mandarin Oriental, Tokyo, offering impeccable service.',
      rating: 4.7,
      address: '2-1-1 Nihonbashi Muromachi, Chuo City, Tokyo 103-8328, Japan',
      opening_hours: '',
      link: 'https://www.mandarinoriental.com/tokyo/nihonbashi/luxury-hotel',
      price_range: '280-550',
    },
    {
      name: 'Andaz Tokyo Toranomon Hills',
      city_name: 'Tokyo',
      category: 'hotel',
      description:
        'Experience contemporary luxury at Andaz Tokyo Toranomon Hills in the heart of the city.',
      rating: 4.6,
      address: '1-23-4 Toranomon, Minato City, Tokyo 105-0001, Japan',
      opening_hours: '',
      link: 'https://www.hyatt.com/en-US/hotel/japan/andaz-tokyo-toranomon-hills/tyoaz',
      price_range: '200-450',
    },
    {
      name: 'The Ritz-Carlton, Tokyo',
      city_name: 'Tokyo',
      category: 'hotel',
      description:
        'Indulge in luxury at The Ritz-Carlton, Tokyo, located in the vibrant Roppongi district.',
      rating: 4.9,
      address: 'Tokyo Midtown 9-7-1 Akasaka Minato-ku, Tokyo 107-6245, Japan',
      opening_hours: '',
      link: 'https://www.ritzcarlton.com/en/hotels/japan/tokyo',
      price_range: '300-600',
    },
    {
      name: 'Eiffel Tower',
      city_name: 'Paris',
      category: 'place',
      description:
        'Visit the iconic Eiffel Tower for breathtaking views of Paris.',
      rating: 4.7,
      address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France',
      opening_hours: '9:30 AM - 11 PM',
      link: 'https://www.toureiffel.paris/en',
      price_range: '',
    },
    {
      name: 'Louvre Museum',
      city_name: 'Paris',
      category: 'place',
      description:
        'Explore the world-renowned Louvre Museum and its vast art collection.',
      rating: 4.8,
      address: 'Rue de Rivoli, 75001 Paris, France',
      opening_hours: '9 AM - 6 PM (Closed on Tuesdays)',
      link: 'https://www.louvre.fr/en/',
      price_range: '',
    },
    {
      name: 'Montmartre',
      city_name: 'Paris',
      category: 'place',
      description:
        'Discover the artistic charm of Montmartre with its narrow streets and lively atmosphere.',
      rating: 4.5,
      address: 'Montmartre, 75018 Paris, France',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'Sainte-Chapelle',
      city_name: 'Paris',
      category: 'place',
      description:
        'Admire the stunning stained glass windows at Sainte-Chapelle, a Gothic masterpiece.',
      rating: 4.6,
      address: '8 Boulevard du Palais, 75001 Paris, France',
      opening_hours: '9 AM - 7 PM',
      link: 'https://www.sainte-chapelle.fr/en/',
      price_range: '',
    },
    {
      name: 'Seine River Cruise',
      city_name: 'Paris',
      category: 'place',
      description:
        'Enjoy a romantic Seine River Cruise for picturesque views of Paris landmarks.',
      rating: 4.4,
      address: 'Various departure points along the Seine',
      opening_hours: 'Depends on the cruise company',
      link: '',
      price_range: '',
    },
    {
      name: 'Le Jules Verne',
      city_name: 'Paris',
      category: 'restaurant',
      description:
        'Dine in elegance at Le Jules Verne, located in the Eiffel Tower with panoramic views.',
      rating: 4.9,
      address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France',
      opening_hours: 'Lunch: 12 PM - 1:30 PM, Dinner: 6:30 PM - 9:30 PM',
      link: 'https://www.lejulesverne-paris.com/',
      price_range: '100-200',
    },
    {
      name: 'Le Comptoir du Relais',
      city_name: 'Paris',
      category: 'restaurant',
      description:
        'Experience French bistro charm at Le Comptoir du Relais in Saint-Germain-des-Prés.',
      rating: 4.6,
      address: "9 Carrefour de l'Odéon, 75006 Paris, France",
      opening_hours: '8 AM - 10:30 PM',
      link: 'https://www.hotel-paris-relais-saint-germain.com/',
      price_range: '40-80',
    },
    {
      name: "L'Ambroisie",
      city_name: 'Paris',
      category: 'restaurant',
      description:
        "Indulge in gourmet French cuisine at L'Ambroisie, a three-star Michelin restaurant.",
      rating: 4.9,
      address: '9 Place des Vosges, 75004 Paris, France',
      opening_hours: 'Lunch: 12:30 PM - 2 PM, Dinner: 7 PM - 9 PM',
      link: 'https://ambroisie-paris.com/',
      price_range: '150-300',
    },
    {
      name: 'Les Deux Magots',
      city_name: 'Paris',
      category: 'restaurant',
      description:
        'Sip coffee in a historic setting at Les Deux Magots, a famous literary café in Saint-Germain-des-Prés.',
      rating: 4.5,
      address: '6 Place Saint-Germain des Prés, 75006 Paris, France',
      opening_hours: '7:30 AM - 1 AM',
      link: 'https://www.lesdeuxmagots.fr/en/',
      price_range: '20-40',
    },
    {
      name: "L'Ambassade de l'Île",
      city_name: 'Paris',
      category: 'restaurant',
      description:
        "Experience gourmet dining at L'Ambassade de l'Île, known for its refined French cuisine.",
      rating: 4.8,
      address: '4 Quai de la Tournelle, 75005 Paris, France',
      opening_hours: 'Lunch: 12 PM - 2:30 PM, Dinner: 7 PM - 10 PM',
      link: 'https://www.ambassadedelile.com/',
      price_range: '80-150',
    },
    {
      name: 'Le Bristol Paris',
      city_name: 'Paris',
      category: 'hotel',
      description:
        'Stay in luxury at Le Bristol Paris, a five-star hotel with exquisite accommodations.',
      rating: 4.9,
      address: '112 Rue du Faubourg Saint-Honoré, 75008 Paris, France',
      opening_hours: '',
      link: 'https://www.oetkercollection.com/hotels/le-bristol-paris/',
      price_range: '400-800',
    },
    {
      name: 'Hotel Plaza Athénée',
      city_name: 'Paris',
      category: 'hotel',
      description:
        'Experience elegance at Hotel Plaza Athénée, located on Avenue Montaigne near Champs-Élysées.',
      rating: 4.8,
      address: '25 Avenue Montaigne, 75008 Paris, France',
      opening_hours: '',
      link: 'https://www.dorchestercollection.com/en/paris/hotel-plaza-athenee/',
      price_range: '500-1000',
    },
    {
      name: 'Shangri-La Hotel Paris',
      city_name: 'Paris',
      category: 'hotel',
      description:
        'Enjoy a luxurious stay at Shangri-La Hotel Paris with stunning views of the Eiffel Tower.',
      rating: 4.7,
      address: "10 Avenue d'Iéna, 75116 Paris, France",
      opening_hours: '',
      link: 'https://www.shangri-la.com/paris/shangrila/',
      price_range: '450-900',
    },
    {
      name: 'Hôtel de Crillon, A Rosewood Hotel',
      city_name: 'Paris',
      category: 'hotel',
      description:
        'Experience opulence at Hôtel de Crillon, a Rosewood Hotel, located on Place de la Concorde.',
      rating: 4.6,
      address: '10 Place de la Concorde, 75008 Paris, France',
      opening_hours: '',
      link: 'https://www.rosewoodhotels.com/en/hotel-de-crillon',
      price_range: '500-1000',
    },
    {
      name: 'Hotel Lutetia',
      city_name: 'Paris',
      category: 'hotel',
      description:
        'Stay in style at Hotel Lutetia, a historic hotel located in Saint-Germain-des-Prés.',
      rating: 4.5,
      address: '45 Boulevard Raspail, 75006 Paris, France',
      opening_hours: '',
      link: 'https://www.hotellutetia.com/',
      price_range: '300-600',
    },
    {
      name: 'Statue of Liberty',
      city_name: 'New York',
      category: 'place',
      description:
        'Visit the iconic Statue of Liberty and explore its rich history.',
      rating: 4.6,
      address: 'Liberty Island, New York, NY 10004, USA',
      opening_hours: '9 AM - 5 PM',
      link: 'https://www.nps.gov/stli/index.htm',
      price_range: '',
    },
    {
      name: 'Central Park',
      city_name: 'New York',
      category: 'place',
      description:
        'Escape the urban hustle in Central Park, a vast green oasis in the heart of Manhattan.',
      rating: 4.8,
      address: 'Central Park, New York, NY 10022, USA',
      opening_hours: '6 AM - 1 AM',
      link: 'https://www.centralparknyc.org/',
      price_range: '',
    },
    {
      name: 'Times Square',
      city_name: 'New York',
      category: 'place',
      description:
        "Experience the vibrant energy of Times Square, the 'Crossroads of the World.'",
      rating: 4.5,
      address: 'Broadway, New York, NY 10036, USA',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'The Metropolitan Museum of Art',
      city_name: 'New York',
      category: 'place',
      description:
        "Explore art spanning over 5,000 years at The Met, one of the world's largest art museums.",
      rating: 4.7,
      address: '1000 Fifth Avenue, New York, NY 10028, USA',
      opening_hours: '10 AM - 5 PM (Closed on Mondays)',
      link: 'https://www.metmuseum.org/',
      price_range: '',
    },
    {
      name: 'One World Observatory',
      city_name: 'New York',
      category: 'place',
      description:
        'Enjoy panoramic views of Manhattan from the One World Observatory at One World Trade Center.',
      rating: 4.6,
      address: '285 Fulton Street, New York, NY 10007, USA',
      opening_hours: '9 AM - 8 PM',
      link: 'https://oneworldobservatory.com/',
      price_range: '',
    },
    {
      name: "Katz's Delicatessen",
      city_name: 'New York',
      category: 'restaurant',
      description:
        "Savor iconic pastrami sandwiches at Katz's Delicatessen, a NYC culinary institution.",
      rating: 4.9,
      address: '205 E Houston Street, New York, NY 10002, USA',
      opening_hours: '24 hours',
      link: 'https://www.katzsdelicatessen.com/',
      price_range: '20-40',
    },
    {
      name: 'Shake Shack',
      city_name: 'New York',
      category: 'restaurant',
      description:
        'Indulge in delicious burgers and shakes at Shake Shack, a popular fast-food chain.',
      rating: 4.7,
      address: 'Madison Square Park, New York, NY 10010, USA',
      opening_hours: '11 AM - 10 PM',
      link: 'https://www.shakeshack.com/',
      price_range: '10-20',
    },
    {
      name: 'Per Se',
      city_name: 'New York',
      category: 'restaurant',
      description:
        'Experience fine dining at Per Se, a three-star Michelin restaurant offering exquisite cuisine.',
      rating: 4.9,
      address: '10 Columbus Circle, New York, NY 10019, USA',
      opening_hours: '5:30 PM - 9:30 PM',
      link: 'https://www.thomaskeller.com/perseny',
      price_range: '250-500',
    },
    {
      name: "Joe's Pizza",
      city_name: 'New York',
      category: 'restaurant',
      description:
        "Taste authentic New York-style pizza at Joe's Pizza, a beloved pizza joint in Greenwich Village.",
      rating: 4.5,
      address: '7 Carmine Street, New York, NY 10014, USA',
      opening_hours: '11 AM - 10 PM',
      link: 'https://www.joespizzanyc.com/',
      price_range: '10-20',
    },
    {
      name: 'Levain Bakery',
      city_name: 'New York',
      category: 'restaurant',
      description:
        'Indulge in delicious cookies and baked goods at Levain Bakery, a local favorite.',
      rating: 4.8,
      address: '167 W 74th Street, New York, NY 10023, USA',
      opening_hours: '8 AM - 7 PM',
      link: 'https://www.levainbakery.com/',
      price_range: '5-15',
    },
    {
      name: 'The St. Regis New York',
      city_name: 'New York',
      category: 'hotel',
      description:
        'Experience luxury at The St. Regis New York, an iconic hotel with timeless elegance.',
      rating: 4.8,
      address: '2 East 55th Street at 5th Avenue, New York, NY 10022, USA',
      opening_hours: '',
      link: 'https://www.marriott.com/hotels/travel/nycxr-the-st-regis-new-york/',
      price_range: '400-800',
    },
    {
      name: 'The Plaza Hotel',
      city_name: 'New York',
      category: 'hotel',
      description:
        'Stay in opulence at The Plaza Hotel, a historic landmark on Fifth Avenue.',
      rating: 4.7,
      address: '768 5th Avenue, New York, NY 10019, USA',
      opening_hours: '',
      link: 'https://www.theplazany.com/',
      price_range: '500-1000',
    },
    {
      name: 'Park Hyatt New York',
      city_name: 'New York',
      category: 'hotel',
      description:
        'Enjoy sophistication at Park Hyatt New York, located near Central Park and Columbus Circle.',
      rating: 4.6,
      address: '153 West 57th Street, New York, NY 10019, USA',
      opening_hours: '',
      link: 'https://www.hyatt.com/en-US/hotel/new-york/park-hyatt-new-york/nycph',
      price_range: '450-900',
    },
    {
      name: 'The Langham, New York, Fifth Avenue',
      city_name: 'New York',
      category: 'hotel',
      description:
        'Experience luxury at The Langham, New York, Fifth Avenue, a refined hotel in Midtown Manhattan.',
      rating: 4.8,
      address: '400 Fifth Avenue, New York, NY 10018, USA',
      opening_hours: '',
      link: 'https://www.langhamhotels.com/en/the-langham/new-york/',
      price_range: '400-800',
    },
    {
      name: 'The NoMad Hotel',
      city_name: 'New York',
      category: 'hotel',
      description:
        'Stay in style at The NoMad Hotel, a chic and sophisticated retreat in the Flatiron District.',
      rating: 4.7,
      address: '1170 Broadway, New York, NY 10001, USA',
      opening_hours: '',
      link: 'https://www.thenomadhotel.com/new-york/',
      price_range: '300-600',
    },
    {
      name: 'Sydney Opera House',
      city_name: 'Sydney',
      category: 'place',
      description:
        'Marvel at the iconic Sydney Opera House, a UNESCO World Heritage site and architectural masterpiece.',
      rating: 4.9,
      address: 'Bennelong Point, Sydney NSW 2000, Australia',
      opening_hours: 'Depends on events',
      link: 'https://www.sydneyoperahouse.com/',
      price_range: '',
    },
    {
      name: 'Bondi Beach',
      city_name: 'Sydney',
      category: 'place',
      description:
        'Relax on the golden sands of Bondi Beach, known for its surf and vibrant beach culture.',
      rating: 4.7,
      address: 'Bondi Beach, Sydney NSW 2026, Australia',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'Sydney Harbour Bridge',
      city_name: 'Sydney',
      category: 'place',
      description:
        'Climb or admire the Sydney Harbour Bridge for breathtaking views of the harbor and city skyline.',
      rating: 4.6,
      address: 'Sydney Harbour Bridge, Sydney NSW 2000, Australia',
      opening_hours: '24 hours',
      link: 'https://www.bridgeclimb.com/',
      price_range: '',
    },
    {
      name: 'Taronga Zoo',
      city_name: 'Sydney',
      category: 'place',
      description:
        'Discover wildlife at Taronga Zoo, home to a diverse range of animals with stunning harbor views.',
      rating: 4.5,
      address: 'Bradleys Head Road, Mosman NSW 2088, Australia',
      opening_hours: '9:30 AM - 4:30 PM',
      link: 'https://taronga.org.au/taronga-zoo',
      price_range: '',
    },
    {
      name: 'Royal Botanic Garden',
      city_name: 'Sydney',
      category: 'place',
      description:
        'Stroll through the lush Royal Botanic Garden, a serene oasis in the heart of Sydney.',
      rating: 4.8,
      address: 'Mrs Macquaries Road, Sydney NSW 2000, Australia',
      opening_hours: '7 AM - 5 PM',
      link: 'https://www.rbgsyd.nsw.gov.au/',
      price_range: '',
    },
    {
      name: 'Quay',
      city_name: 'Sydney',
      category: 'restaurant',
      description:
        'Dine at Quay, a world-renowned restaurant offering modern Australian cuisine with stunning harbor views.',
      rating: 4.9,
      address:
        'Upper Level, Overseas Passenger Terminal, The Rocks, Sydney NSW 2000, Australia',
      opening_hours: 'Lunch: 12 PM - 2:30 PM, Dinner: 6 PM - 10 PM',
      link: 'https://www.quay.com.au/',
      price_range: '150-300',
    },
    {
      name: "Tetsuya's",
      city_name: 'Sydney',
      category: 'restaurant',
      description:
        "Experience Japanese-inspired French cuisine at Tetsuya's, a fine-dining restaurant in the heart of Sydney.",
      rating: 4.8,
      address: '529 Kent Street, Sydney NSW 2000, Australia',
      opening_hours: '6 PM - 10 PM',
      link: 'https://www.tetsuyas.com/',
      price_range: '200-400',
    },
    {
      name: 'Bennelong Restaurant',
      city_name: 'Sydney',
      category: 'restaurant',
      description:
        'Dine at Bennelong Restaurant, located in the Sydney Opera House, offering modern Australian cuisine.',
      rating: 4.7,
      address:
        'Sydney Opera House, Bennelong Point, Sydney NSW 2000, Australia',
      opening_hours: 'Lunch: 12 PM - 2 PM, Dinner: 5:30 PM - 9 PM',
      link: 'https://www.bennelong.com.au/',
      price_range: '100-200',
    },
    {
      name: 'Golden Century Seafood Restaurant',
      city_name: 'Sydney',
      category: 'restaurant',
      description:
        'Indulge in fresh seafood at Golden Century, a popular Chinese seafood restaurant in Sydney.',
      rating: 4.6,
      address: '393-399 Sussex Street, Sydney NSW 2000, Australia',
      opening_hours: '12 PM - 2 AM',
      link: 'https://www.goldencentury.com.au/',
      price_range: '50-100',
    },
    {
      name: 'The Grounds of Alexandria',
      city_name: 'Sydney',
      category: 'restaurant',
      description:
        'Experience a unique dining experience at The Grounds of Alexandria, a popular café with beautiful gardens.',
      rating: 4.8,
      address: '7A/2 Huntley Street, Alexandria NSW 2015, Australia',
      opening_hours: '7 AM - 9 PM',
      link: 'https://thegrounds.com.au/',
      price_range: '20-40',
    },
    {
      name: 'Park Hyatt Sydney',
      city_name: 'Sydney',
      category: 'hotel',
      description:
        'Stay in luxury at Park Hyatt Sydney, overlooking the Sydney Opera House and Sydney Harbour Bridge.',
      rating: 4.9,
      address: '7 Hickson Road, The Rocks, Sydney NSW 2000, Australia',
      opening_hours: '',
      link: 'https://www.hyatt.com/en-US/hotel/australia/park-hyatt-sydney/sydph',
      price_range: '500-1000',
    },
    {
      name: 'Shangri-La Hotel Sydney',
      city_name: 'Sydney',
      category: 'hotel',
      description:
        'Enjoy panoramic views of Sydney Harbour at Shangri-La Hotel, located in The Rocks.',
      rating: 4.8,
      address: '176 Cumberland Street, The Rocks, Sydney NSW 2000, Australia',
      opening_hours: '',
      link: 'https://www.shangri-la.com/sydney/shangrila/',
      price_range: '400-800',
    },
    {
      name: 'Four Seasons Hotel Sydney',
      city_name: 'Sydney',
      category: 'hotel',
      description:
        'Experience luxury at Four Seasons Hotel Sydney, located in Circular Quay with stunning harbor views.',
      rating: 4.7,
      address: '199 George Street, Sydney NSW 2000, Australia',
      opening_hours: '',
      link: 'https://www.fourseasons.com/sydney/',
      price_range: '400-800',
    },
    {
      name: 'InterContinental Sydney',
      city_name: 'Sydney',
      category: 'hotel',
      description:
        'Stay in elegance at InterContinental Sydney, a historic hotel overlooking Circular Quay.',
      rating: 4.6,
      address: '117 Macquarie Street, Sydney NSW 2000, Australia',
      opening_hours: '',
      link: 'https://www.ihg.com/intercontinental/hotels/us/en/sydney/sydha/hoteldetail',
      price_range: '300-600',
    },
    {
      name: 'Pier One Sydney Harbour, Autograph Collection',
      city_name: 'Sydney',
      category: 'hotel',
      description:
        'Experience waterfront luxury at Pier One Sydney Harbour, Autograph Collection.',
      rating: 4.7,
      address: '11 Hickson Road, Walsh Bay, Sydney NSW 2000, Australia',
      opening_hours: '',
      link: 'https://www.marriott.com.au/hotels/travel/sydsi-pier-one-sydney-harbour-autograph-collection/',
      price_range: '300-600',
    },
    {
      name: 'Colosseum',
      city_name: 'Rome',
      category: 'place',
      description:
        'Explore the ancient Colosseum, a symbol of Roman engineering and a UNESCO World Heritage site.',
      rating: 4.8,
      address: 'Piazza del Colosseo, 1, 00184 Rome, Italy',
      opening_hours: '8:30 AM - 4:30 PM',
      link: 'https://www.coopculture.it/en/colosseo-e-shop.cfm',
      price_range: '',
    },
    {
      name: 'Vatican City',
      city_name: 'Rome',
      category: 'place',
      description:
        "Visit Vatican City, home to St. Peter's Basilica, the Vatican Museums, and the Sistine Chapel.",
      rating: 4.9,
      address: 'Vatican City, 00120',
      opening_hours: 'Depends on attractions',
      link: 'http://www.vatican.va/content/vatican/en.html',
      price_range: '',
    },
    {
      name: 'Trevi Fountain',
      city_name: 'Rome',
      category: 'place',
      description:
        'Throw a coin into the iconic Trevi Fountain to ensure a return to Rome, a timeless tradition.',
      rating: 4.7,
      address: 'Piazza di Trevi, 00187 Rome, Italy',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'Roman Forum',
      city_name: 'Rome',
      category: 'place',
      description:
        "Step back in time at the Roman Forum, the ancient heart of Rome's political and social life.",
      rating: 4.6,
      address: 'Via della Salara Vecchia, 5/6, 00186 Rome, Italy',
      opening_hours: '8:30 AM - 4:30 PM',
      link: 'https://www.coopculture.it/en/colosseo-e-shop.cfm',
      price_range: '',
    },
    {
      name: 'Pantheon',
      city_name: 'Rome',
      category: 'place',
      description:
        'Admire the architectural marvel of the Pantheon, a well-preserved ancient Roman temple.',
      rating: 4.8,
      address: 'Piazza della Rotonda, 00186 Rome, Italy',
      opening_hours: '8:30 AM - 7:30 PM',
      link: '',
      price_range: '',
    },
    {
      name: 'La Pergola',
      city_name: 'Rome',
      category: 'restaurant',
      description:
        'Experience Michelin-starred dining at La Pergola, located atop Rome Cavalieri, a Waldorf Astoria Hotel.',
      rating: 4.9,
      address: 'Via Alberto Cadlolo, 101, 00136 Rome, Italy',
      opening_hours: 'Dinner: 7:30 PM - 10:30 PM',
      link: 'https://romecavalieri.com/dining/la-pergola/',
      price_range: '200-400',
    },
    {
      name: 'Roscioli',
      city_name: 'Rome',
      category: 'restaurant',
      description:
        'Indulge in authentic Roman cuisine at Roscioli, a renowned trattoria in the heart of Rome.',
      rating: 4.7,
      address: 'Piazza Benedetto Cairoli, 16, 00186 Rome, Italy',
      opening_hours: 'Lunch: 12:30 PM - 3 PM, Dinner: 7 PM - 11 PM',
      link: 'https://www.salumeriaroscioli.com/',
      price_range: '50-100',
    },
    {
      name: 'Da Enzo al 29',
      city_name: 'Rome',
      category: 'restaurant',
      description:
        'Enjoy traditional Roman dishes at Da Enzo al 29, a charming family-run trattoria in Trastevere.',
      rating: 4.6,
      address: 'Via dei Vascellari, 29, 00153 Rome, Italy',
      opening_hours: '12:30 PM - 3 PM, 7:30 PM - 11 PM',
      link: 'https://www.daenzoal29.com/',
      price_range: '30-60',
    },
    {
      name: 'Antico Forno Roscioli',
      city_name: 'Rome',
      category: 'restaurant',
      description:
        'Savor delicious Roman-style pizza and baked goods at Antico Forno Roscioli.',
      rating: 4.5,
      address: 'Via dei Chiavari, 34, 00186 Rome, Italy',
      opening_hours: '7 AM - 7:30 PM',
      link: 'https://www.anticofornoroscioli.com/',
      price_range: '10-20',
    },
    {
      name: 'Pierluigi',
      city_name: 'Rome',
      category: 'restaurant',
      description:
        'Dine in a historic setting at Pierluigi, known for its seafood and Roman specialties.',
      rating: 4.8,
      address: "Piazza de' Ricci, 144, 00186 Rome, Italy",
      opening_hours: '12 PM - 12 AM',
      link: 'https://www.pierluigi.it/',
      price_range: '100-200',
    },
    {
      name: 'Hotel de Russie, a Rocco Forte Hotel',
      city_name: 'Rome',
      category: 'hotel',
      description:
        'Experience luxury at Hotel de Russie, a Rocco Forte Hotel, located near the Spanish Steps.',
      rating: 4.8,
      address: 'Via del Babuino, 9, 00187 Rome, Italy',
      opening_hours: '',
      link: 'https://www.roccofortehotels.com/hotel-de-russie/',
      price_range: '400-800',
    },
    {
      name: 'The St. Regis Rome',
      city_name: 'Rome',
      category: 'hotel',
      description:
        'Stay in timeless elegance at The St. Regis Rome, a luxury hotel on Via Vittorio Emanuele Orlando.',
      rating: 4.7,
      address: 'Via Vittorio Emanuele Orlando, 3, 00185 Rome, Italy',
      opening_hours: '',
      link: 'https://www.marriott.com/hotels/travel/romxr-the-st-regis-rome/',
      price_range: '300-600',
    },
    {
      name: 'Hotel Hassler Roma',
      city_name: 'Rome',
      category: 'hotel',
      description:
        'Enjoy panoramic views of Rome from Hotel Hassler Roma, a luxury hotel near the Spanish Steps.',
      rating: 4.9,
      address: 'Piazza Trinità dei Monti, 6, 00187 Rome, Italy',
      opening_hours: '',
      link: 'https://www.hotelhasslerroma.com/',
      price_range: '500-1000',
    },
    {
      name: 'Palazzo Manfredi - Small Luxury Hotels of the World',
      city_name: 'Rome',
      category: 'hotel',
      description:
        'Experience luxury and history at Palazzo Manfredi, a boutique hotel overlooking the Colosseum.',
      rating: 4.8,
      address: 'Via Labicana, 125, 00184 Rome, Italy',
      opening_hours: '',
      link: 'https://www.palazzomanfredi.com/',
      price_range: '300-600',
    },
    {
      name: 'Hotel Eden - Dorchester Collection',
      city_name: 'Rome',
      category: 'hotel',
      description:
        'Stay in refined elegance at Hotel Eden, a Dorchester Collection hotel near Villa Borghese.',
      rating: 4.7,
      address: 'Via Ludovisi, 49, 00187 Rome, Italy',
      opening_hours: '',
      link: 'https://www.dorchestercollection.com/en/rome/hotel-eden/',
      price_range: '400-800',
    },
    {
      name: 'Burj Khalifa',
      city_name: 'Dubai',
      category: 'place',
      description:
        "Experience breathtaking views from the world's tallest building, the Burj Khalifa.",
      rating: 4.9,
      address: '1 Sheikh Mohammed bin Rashid Blvd, Dubai, United Arab Emirates',
      opening_hours: '10 AM - 12 AM',
      link: 'https://www.burjkhalifa.ae/en/',
      price_range: '',
    },
    {
      name: 'The Dubai Mall',
      city_name: 'Dubai',
      category: 'place',
      description:
        'Shop, dine, and explore at The Dubai Mall, one of the largest shopping and entertainment destinations.',
      rating: 4.8,
      address: 'Downtown Dubai, Dubai, United Arab Emirates',
      opening_hours: '10 AM - 12 AM',
      link: 'https://thedubaimall.com/',
      price_range: '',
    },
    {
      name: 'Palm Jumeirah',
      city_name: 'Dubai',
      category: 'place',
      description:
        'Relax on the stunning Palm Jumeirah, an artificial archipelago known for luxury resorts and pristine beaches.',
      rating: 4.7,
      address: 'Palm Jumeirah, Dubai, United Arab Emirates',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'Dubai Marina',
      city_name: 'Dubai',
      category: 'place',
      description:
        'Stroll along the waterfront promenade of Dubai Marina, surrounded by skyscrapers and luxury yachts.',
      rating: 4.6,
      address: 'Dubai Marina, Dubai, United Arab Emirates',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'The Dubai Fountain',
      city_name: 'Dubai',
      category: 'place',
      description:
        'Witness the mesmerizing water and light show at The Dubai Fountain, located near the Burj Khalifa.',
      rating: 4.8,
      address: 'Burj Khalifa Lake, Downtown Dubai, Dubai, United Arab Emirates',
      opening_hours: '6 PM - 11 PM',
      link: 'https://www.thedubaimall.com/en/attractions/the-dubai-fountain',
      price_range: '',
    },
    {
      name: 'At.mosphere',
      city_name: 'Dubai',
      category: 'restaurant',
      description:
        'Dine at At.mosphere, located on the 122nd floor of the Burj Khalifa, offering fine dining with panoramic views.',
      rating: 4.9,
      address: 'Burj Khalifa, Downtown Dubai, Dubai, United Arab Emirates',
      opening_hours: 'Lunch: 12:30 PM - 3 PM, Dinner: 6:30 PM - 10:30 PM',
      link: 'https://www.atmosphereburjkhalifa.com/',
      price_range: '300-600',
    },
    {
      name: 'Pierchic',
      city_name: 'Dubai',
      category: 'restaurant',
      description:
        'Indulge in seafood at Pierchic, a unique overwater dining experience with stunning views of the Arabian Gulf.',
      rating: 4.8,
      address: 'Al Qasr, Madinat Jumeirah, Dubai, United Arab Emirates',
      opening_hours: 'Lunch: 12 PM - 3 PM, Dinner: 6:30 PM - 10:30 PM',
      link: 'https://www.pierchic.com/',
      price_range: '200-400',
    },
    {
      name: 'Nobu Dubai',
      city_name: 'Dubai',
      category: 'restaurant',
      description:
        'Experience Japanese-Peruvian fusion cuisine at Nobu Dubai, located in Atlantis, The Palm.',
      rating: 4.7,
      address:
        'Atlantis The Palm, Crescent Road, The Palm Jumeirah, Dubai, United Arab Emirates',
      opening_hours: '6 PM - 11 PM',
      link: 'https://www.atlantis.com/dubai/restaurants/nobu',
      price_range: '150-300',
    },
    {
      name: 'Zuma Dubai',
      city_name: 'Dubai',
      category: 'restaurant',
      description:
        'Enjoy contemporary Japanese cuisine at Zuma Dubai, a stylish and popular dining destination.',
      rating: 4.6,
      address: 'Gate Village 06, DIFC, Dubai, United Arab Emirates',
      opening_hours: '12:30 PM - 12 AM',
      link: 'https://www.zumarestaurant.com/zuma-landing/dubai/en/welcome',
      price_range: '100-200',
    },
    {
      name: 'Al Hadheerah',
      city_name: 'Dubai',
      category: 'restaurant',
      description:
        'Experience Arabian dining at Al Hadheerah, an open-air desert restaurant at Bab Al Shams Desert Resort.',
      rating: 4.8,
      address:
        'Bab Al Shams Desert Resort & Spa, Al Marmoom, Dubai, United Arab Emirates',
      opening_hours: '7 PM - 11:30 PM',
      link: 'https://www.meydanhotels.com/babalshams/dining/al-hadheerah',
      price_range: '150-300',
    },
    {
      name: 'Burj Al Arab Jumeirah',
      city_name: 'Dubai',
      category: 'hotel',
      description:
        'Experience luxury at Burj Al Arab Jumeirah, an iconic sail-shaped hotel on its own island.',
      rating: 4.9,
      address: 'Jumeirah Street, Umm Suqeim, Dubai, United Arab Emirates',
      opening_hours: '',
      link: 'https://www.jumeirah.com/en/stay/dubai/burj-al-arab-jumeirah',
      price_range: '1000-2000',
    },
    {
      name: 'Atlantis The Palm',
      city_name: 'Dubai',
      category: 'hotel',
      description:
        'Stay in a resort paradise at Atlantis The Palm, located on the Palm Jumeirah.',
      rating: 4.8,
      address: 'Crescent Road, The Palm Jumeirah, Dubai, United Arab Emirates',
      opening_hours: '',
      link: 'https://www.atlantis.com/dubai/',
      price_range: '500-1000',
    },
    {
      name: 'Armani Hotel Dubai',
      city_name: 'Dubai',
      category: 'hotel',
      description:
        'Experience luxury and sophistication at Armani Hotel Dubai, located in the Burj Khalifa.',
      rating: 4.7,
      address: 'Burj Khalifa, Downtown Dubai, Dubai, United Arab Emirates',
      opening_hours: '',
      link: 'https://www.armanihoteldubai.com/',
      price_range: '400-800',
    },
    {
      name: 'Jumeirah Al Qasr - Madinat Jumeirah',
      city_name: 'Dubai',
      category: 'hotel',
      description:
        'Stay in Arabian luxury at Jumeirah Al Qasr, part of the Madinat Jumeirah resort complex.',
      rating: 4.6,
      address: 'Madinat Jumeirah, Al Sufouh Road, Dubai, United Arab Emirates',
      opening_hours: '',
      link: 'https://www.jumeirah.com/en/stay/dubai/jumeirah-al-qasr',
      price_range: '300-600',
    },
    {
      name: 'Palazzo Versace Dubai',
      city_name: 'Dubai',
      category: 'hotel',
      description:
        'Experience the glamour of Palazzo Versace Dubai, a luxury hotel on the shores of the Dubai Creek.',
      rating: 4.7,
      address: 'Cultural Village, Al Jadaf, Dubai, United Arab Emirates',
      opening_hours: '',
      link: 'https://www.palazzoversace.ae/',
      price_range: '300-600',
    },
    {
      name: 'Hagia Sophia',
      city_name: 'Istanbul',
      category: 'place',
      description:
        'Explore the iconic Hagia Sophia, a UNESCO World Heritage site with a rich history as a church and mosque.',
      rating: 4.8,
      address: 'Sultan Ahmet, Ayasofya Meydanı, 34122 Istanbul, Turkey',
      opening_hours: '9 AM - 7 PM',
      link: 'https://www.hagiasophia.com/',
      price_range: '',
    },
    {
      name: 'Topkapi Palace',
      city_name: 'Istanbul',
      category: 'place',
      description:
        'Visit Topkapi Palace, a historic palace complex that served as the residence of Ottoman sultans for centuries.',
      rating: 4.9,
      address: 'Topkapi Sarayi, Gulhane Park, 34122 Istanbul, Turkey',
      opening_hours: '9 AM - 5 PM',
      link: 'https://topkapisarayi.gov.tr/',
      price_range: '',
    },
    {
      name: 'Blue Mosque',
      city_name: 'Istanbul',
      category: 'place',
      description:
        'Admire the stunning architecture of the Blue Mosque, officially known as the Sultan Ahmed Mosque.',
      rating: 4.7,
      address: 'Sultan Ahmet, Atmeydanı Cd. No:7, 34122 Istanbul, Turkey',
      opening_hours: 'Open for prayers',
      link: '',
      price_range: '',
    },
    {
      name: 'Grand Bazaar',
      city_name: 'Istanbul',
      category: 'place',
      description:
        "Experience the vibrant atmosphere of the Grand Bazaar, one of the world's oldest and largest covered markets.",
      rating: 4.6,
      address: 'Beyazit, Kalpakcilar Cd. No:22, 34126 Istanbul, Turkey',
      opening_hours: '9 AM - 7 PM',
      link: 'https://grandbazaaristanbul.org/',
      price_range: '',
    },
    {
      name: 'Bosphorus Cruise',
      city_name: 'Istanbul',
      category: 'place',
      description:
        "Take a scenic Bosphorus Cruise to enjoy panoramic views of Istanbul's skyline and historic landmarks.",
      rating: 4.8,
      address: 'Bosphorus Strait, Istanbul, Turkey',
      opening_hours: 'Depends on cruise operators',
      link: '',
      price_range: '',
    },
    {
      name: 'Mikla Restaurant',
      city_name: 'Istanbul',
      category: 'restaurant',
      description:
        'Dine at Mikla Restaurant, located on the rooftop of the Marmara Pera Hotel, offering modern Turkish cuisine.',
      rating: 4.9,
      address: 'Mesrutiyet Caddesi, Tepebasi, Beyoglu, 34430 Istanbul, Turkey',
      opening_hours: 'Lunch: 12 PM - 2:30 PM, Dinner: 6:30 PM - 10:30 PM',
      link: 'https://www.miklarestaurant.com/',
      price_range: '150-300',
    },
    {
      name: 'Ciya Sofrası',
      city_name: 'Istanbul',
      category: 'restaurant',
      description:
        'Experience traditional Turkish flavors at Ciya Sofrası, a popular restaurant with a diverse menu.',
      rating: 4.8,
      address: 'Güneşlibahçe Sokak No:43, 34660 Istanbul, Turkey',
      opening_hours: '11 AM - 10 PM',
      link: 'https://ciya.com.tr/en/',
      price_range: '50-100',
    },
    {
      name: '360 Istanbul',
      city_name: 'Istanbul',
      category: 'restaurant',
      description:
        'Enjoy panoramic views of Istanbul at 360 Istanbul, a restaurant and club in the heart of the city.',
      rating: 4.7,
      address:
        'İstiklal Caddesi Mısır Apartmanı Kat:8 No:311, 34430 Istanbul, Turkey',
      opening_hours: 'Lunch: 12 PM - 3:30 PM, Dinner: 6:30 PM - 12 AM',
      link: 'http://www.360istanbul.com/',
      price_range: '100-200',
    },
    {
      name: 'Asitane Restaurant',
      city_name: 'Istanbul',
      category: 'restaurant',
      description:
        'Indulge in Ottoman cuisine at Asitane Restaurant, known for its historical recipes and elegant ambiance.',
      rating: 4.8,
      address: 'Kariye Camii Sokak No:6, Edirnekapi, 34087 Istanbul, Turkey',
      opening_hours: '12 PM - 11 PM',
      link: 'http://www.asitanerestaurant.com/',
      price_range: '100-200',
    },
    {
      name: 'Karadeniz Pide ve Döner Salonu',
      city_name: 'Istanbul',
      category: 'restaurant',
      description:
        'Savor Turkish pide and döner at Karadeniz Pide ve Döner Salonu, a local favorite in Istanbul.',
      rating: 4.6,
      address:
        'Firuzaga Mahallesi, Çukurcuma Cd. No:51, 34425 Istanbul, Turkey',
      opening_hours: '11 AM - 11 PM',
      link: '',
      price_range: '20-40',
    },
    {
      name: 'Hotel Ibrahim Pasha',
      city_name: 'Istanbul',
      category: 'hotel',
      description:
        'Experience boutique luxury at Hotel Ibrahim Pasha, located in the historic Sultanahmet district.',
      rating: 4.8,
      address: 'Terzihane Sk. No:7, 34400 Istanbul, Turkey',
      opening_hours: '',
      link: 'https://www.hotelibrahimpasha.com/',
      price_range: '150-300',
    },
    {
      name: 'Vault Karakoy House Hotel',
      city_name: 'Istanbul',
      category: 'hotel',
      description:
        'Stay in style at Vault Karakoy House Hotel, a boutique hotel in the vibrant Karakoy neighborhood.',
      rating: 4.7,
      address: 'Bankalar Cd. No:5, 34420 Istanbul, Turkey',
      opening_hours: '',
      link: 'https://www.vaulthotel.com/',
      price_range: '200-400',
    },
    {
      name: 'The Ritz-Carlton, Istanbul',
      city_name: 'Istanbul',
      category: 'hotel',
      description:
        'Experience luxury at The Ritz-Carlton, Istanbul, located in the prestigious Dolmabahce district.',
      rating: 4.7,
      address:
        'Suzer Plaza, Elmadag Askerocagi Cad. No: 15, 34367 Istanbul, Turkey',
      opening_hours: '',
      link: 'https://www.ritzcarlton.com/en/hotels/europe/istanbul',
      price_range: '300-600',
    },
    {
      name: 'Sumahan on the Water',
      city_name: 'Istanbul',
      category: 'hotel',
      description:
        'Stay in a waterfront boutique hotel at Sumahan on the Water, situated on the Asian side of the Bosphorus.',
      rating: 4.6,
      address: 'Kuleli Caddesi No. 51, Çengelköy, 34684 Istanbul, Turkey',
      opening_hours: '',
      link: 'https://www.sumahan.com/',
      price_range: '200-400',
    },
    {
      name: 'Ajwa Hotel Sultanahmet',
      city_name: 'Istanbul',
      category: 'hotel',
      description:
        'Experience Ottoman-inspired luxury at Ajwa Hotel Sultanahmet, located near the Blue Mosque.',
      rating: 4.9,
      address: 'Eminönü Caddesi No:34, 34122 Istanbul, Turkey',
      opening_hours: '',
      link: 'https://www.ajwa.com.tr/',
      price_range: '300-600',
    },
    {
      name: 'Marina Bay Sands',
      city_name: 'Singapore',
      category: 'place',
      description:
        'Experience luxury and entertainment at Marina Bay Sands, featuring a casino, shopping, and the iconic rooftop pool.',
      rating: 4.8,
      address: '10 Bayfront Avenue, Singapore 018956',
      opening_hours: '24 hours',
      link: 'https://www.marinabaysands.com/',
      price_range: '',
    },
    {
      name: 'Gardens by the Bay',
      city_name: 'Singapore',
      category: 'place',
      description:
        'Explore the futuristic Gardens by the Bay, home to the iconic Supertree Grove and Cloud Forest Dome.',
      rating: 4.9,
      address: '18 Marina Gardens Drive, Singapore 018953',
      opening_hours: '5 AM - 2 AM',
      link: 'https://www.gardensbythebay.com.sg/',
      price_range: '',
    },
    {
      name: 'Sentosa Island',
      city_name: 'Singapore',
      category: 'place',
      description:
        'Relax and have fun at Sentosa Island, a resort island with beaches, attractions, and entertainment.',
      rating: 4.7,
      address: 'Sentosa Island, Singapore',
      opening_hours: 'Depends on attractions',
      link: 'https://www.sentosa.com.sg/',
      price_range: '',
    },
    {
      name: 'Singapore Zoo',
      city_name: 'Singapore',
      category: 'place',
      description:
        'Visit the award-winning Singapore Zoo, home to a diverse collection of animals in a naturalistic environment.',
      rating: 4.6,
      address: '80 Mandai Lake Road, Singapore 729826',
      opening_hours: '8:30 AM - 6 PM',
      link: 'https://www.wrs.com.sg/en/singapore-zoo.html',
      price_range: '',
    },
    {
      name: 'Universal Studios Singapore',
      city_name: 'Singapore',
      category: 'place',
      description:
        'Enjoy thrilling rides and attractions at Universal Studios Singapore, located on Sentosa Island.',
      rating: 4.8,
      address: '8 Sentosa Gateway, Singapore 098269',
      opening_hours: '10 AM - 7 PM',
      link: 'https://www.rwsentosa.com/en/attractions/universal-studios-singapore',
      price_range: '',
    },
    {
      name: 'Odette',
      city_name: 'Singapore',
      category: 'restaurant',
      description:
        'Dine at Odette, a Michelin-starred restaurant offering modern French cuisine with Asian influences.',
      rating: 4.9,
      address: "1 St Andrew's Road, #01-04 National Gallery, Singapore 178957",
      opening_hours: 'Lunch: 12 PM - 1:30 PM, Dinner: 7 PM - 9 PM',
      link: 'https://www.odetterestaurant.com/',
      price_range: '300-600',
    },
    {
      name: 'Lau Pa Sat',
      city_name: 'Singapore',
      category: 'restaurant',
      description:
        "Experience local hawker delights at Lau Pa Sat, a historic food center in the heart of Singapore's business district.",
      rating: 4.8,
      address: '18 Raffles Quay, Singapore 048582',
      opening_hours: '24 hours',
      link: 'https://www.laupasat.biz/',
      price_range: '10-30',
    },
    {
      name: 'Burnt Ends',
      city_name: 'Singapore',
      category: 'restaurant',
      description:
        'Savor modern Australian barbecue at Burnt Ends, a Michelin-starred restaurant known for its open kitchen concept.',
      rating: 4.7,
      address: '20 Teck Lim Road, Singapore 088391',
      opening_hours: 'Lunch: 11:45 AM - 1:45 PM, Dinner: 6 PM - 9:30 PM',
      link: 'https://burntends.com.sg/',
      price_range: '50-100',
    },
    {
      name: 'Tim Ho Wan',
      city_name: 'Singapore',
      category: 'restaurant',
      description:
        'Indulge in dim sum delights at Tim Ho Wan, a Michelin-starred restaurant known for its signature dishes.',
      rating: 4.7,
      address: '68 Orchard Road, #01-29A Plaza Singapura, Singapore 238839',
      opening_hours: '10 AM - 10 PM',
      link: 'https://www.timhowan.com/',
      price_range: '20-40',
    },
    {
      name: 'Jumbo Seafood',
      city_name: 'Singapore',
      category: 'restaurant',
      description:
        'Indulge in Singaporean chili crab at Jumbo Seafood, a popular restaurant with a waterfront setting.',
      rating: 4.6,
      address: '30 Merchant Road, # 01-01/02 Riverside Point, Singapore 058282',
      opening_hours: '12 PM - 3 PM, 6 PM - 12 AM',
      link: 'https://www.jumboseafood.com.sg/',
      price_range: '30-60',
    },
    {
      name: 'Raffles Hotel Singapore',
      city_name: 'Singapore',
      category: 'hotel',
      description:
        'Experience colonial charm at Raffles Hotel Singapore, an iconic luxury hotel with a storied history.',
      rating: 4.8,
      address: '1 Beach Road, Singapore 189673',
      opening_hours: '',
      link: 'https://www.raffles.com/singapore/',
      price_range: '400-800',
    },
    {
      name: 'Marina Bay Sands Hotel',
      city_name: 'Singapore',
      category: 'hotel',
      description:
        'Stay in luxury at Marina Bay Sands Hotel, an iconic resort with stunning views of the city skyline.',
      rating: 4.7,
      address: '10 Bayfront Avenue, Singapore 018956',
      opening_hours: '',
      link: 'https://www.marinabaysands.com/',
      price_range: '300-600',
    },
    {
      name: 'The Fullerton Hotel Singapore',
      city_name: 'Singapore',
      category: 'hotel',
      description:
        'Experience heritage luxury at The Fullerton Hotel Singapore, a historic building by the Singapore River.',
      rating: 4.7,
      address: '1 Fullerton Square, Singapore 049178',
      opening_hours: '',
      link: 'https://www.fullertonhotels.com/',
      price_range: '300-600',
    },
    {
      name: 'Capella Singapore',
      city_name: 'Singapore',
      category: 'hotel',
      description:
        'Escape to luxury at Capella Singapore, a resort on Sentosa Island with colonial-style architecture.',
      rating: 4.8,
      address: '1 The Knolls, Sentosa Island, Singapore 098297',
      opening_hours: '',
      link: 'https://www.capellahotels.com/en/capella-singapore',
      price_range: '500-1000',
    },
    {
      name: 'The St. Regis Singapore',
      city_name: 'Singapore',
      category: 'hotel',
      description:
        "Stay in elegance at The St. Regis Singapore, a luxury hotel in the heart of the city's shopping district.",
      rating: 4.6,
      address: '29 Tanglin Road, Singapore 247911',
      opening_hours: '',
      link: 'https://www.marriott.com/hotels/travel/sinxr-the-st-regis-singapore/',
      price_range: '400-800',
    },
    {
      name: 'Te Papa Tongarewa',
      city_name: 'Wellington',
      category: 'place',
      description:
        "Explore New Zealand's national museum, Te Papa Tongarewa, showcasing art, history, and Maori culture.",
      rating: 4.8,
      address: '55 Cable Street, Wellington 6011, New Zealand',
      opening_hours: '10 AM - 6 PM',
      link: 'https://www.tepapa.govt.nz/',
      price_range: '',
    },
    {
      name: 'Mount Victoria Lookout',
      city_name: 'Wellington',
      category: 'place',
      description:
        'Enjoy panoramic views of Wellington from Mount Victoria Lookout, a popular hilltop destination.',
      rating: 4.9,
      address: 'Lookout Road, Hataitai, Wellington 6021, New Zealand',
      opening_hours: '24 hours',
      link: '',
      price_range: '',
    },
    {
      name: 'Wellington Cable Car',
      city_name: 'Wellington',
      category: 'place',
      description:
        'Take a scenic ride on the Wellington Cable Car, offering stunning views of the city and harbor.',
      rating: 4.7,
      address: '280 Lambton Quay, Wellington 6011, New Zealand',
      opening_hours: '7 AM - 10 PM',
      link: 'https://www.wellingtoncablecar.co.nz/',
      price_range: '',
    },
    {
      name: 'Zealandia',
      city_name: 'Wellington',
      category: 'place',
      description:
        "Explore the native wildlife sanctuary Zealandia, dedicated to conserving New Zealand's unique flora and fauna.",
      rating: 4.6,
      address: '53 Waiapu Road, Karori, Wellington 6012, New Zealand',
      opening_hours: '9 AM - 5 PM',
      link: 'https://www.visitzealandia.com/',
      price_range: '',
    },
    {
      name: 'Weta Cave',
      city_name: 'Wellington',
      category: 'place',
      description:
        'Discover the world of Weta Workshop, known for its special effects and props in films like The Lord of the Rings.',
      rating: 4.8,
      address: '1 Weka Street, Miramar, Wellington 6022, New Zealand',
      opening_hours: '9 AM - 5:30 PM',
      link: 'https://www.wetanz.com/',
      price_range: '',
    },
    {
      name: 'Logan Brown',
      city_name: 'Wellington',
      category: 'restaurant',
      description:
        'Dine at Logan Brown, a renowned restaurant housed in a historic bank building, offering modern New Zealand cuisine.',
      rating: 4.9,
      address: '192 Cuba Street, Wellington 6011, New Zealand',
      opening_hours: 'Lunch: 12 PM - 2:30 PM, Dinner: 5:30 PM - 10 PM',
      link: 'https://www.loganbrown.co.nz/',
      price_range: '50-100',
    },
    {
      name: 'Ortega Fish Shack',
      city_name: 'Wellington',
      category: 'restaurant',
      description:
        'Experience seafood delights at Ortega Fish Shack, known for its fresh and sustainable seafood dishes.',
      rating: 4.8,
      address:
        '16 Majoribanks Street, Mount Victoria, Wellington 6011, New Zealand',
      opening_hours: 'Lunch: 12 PM - 3 PM, Dinner: 5:30 PM - 10 PM',
      link: 'https://ortega.co.nz/',
      price_range: '30-60',
    },
    {
      name: 'Noble Rot Wine Bar',
      city_name: 'Wellington',
      category: 'restaurant',
      description:
        'Sip on fine wines at Noble Rot Wine Bar, offering a curated selection and stunning views of the city.',
      rating: 4.7,
      address: '6 Swan Lane, Te Aro, Wellington 6011, New Zealand',
      opening_hours: '4 PM - 12 AM',
      link: 'https://www.noblerot.co.nz/',
      price_range: '40-80',
    },
    {
      name: "Whitebait Restaurant",
      city_name: "Wellington",
      category: "restaurant",
      description: "Savor seafood delicacies at Whitebait Restaurant, known for its elegant setting and fresh, local ingredients.",
      rating: 4.7,
      address: "1 Clyde Quay Wharf, Te Aro, Wellington 6011, New Zealand",
      opening_hours: "Lunch: 12 PM - 3 PM, Dinner: 5:30 PM - 10 PM",
      link: "https://www.white-bait.nz/",
      price_range: "60-120"
    },
    {
      name: 'Wharekauhau Country Estate',
      city_name: 'Wellington',
      category: 'restaurant',
      description:
        'Indulge in gourmet cuisine at Wharekauhau Country Estate, a luxury lodge with breathtaking coastal views.',
      rating: 4.6,
      address:
        'Ocean Beach Road, Palliser Bay, RD3, Featherston 5773, New Zealand',
      opening_hours: '',
      link: 'https://www.wharekauhau.co.nz/',
      price_range: '100-200',
    },
    {
      name: 'QT Wellington',
      city_name: 'Wellington',
      category: 'hotel',
      description:
        'Experience quirky luxury at QT Wellington, a stylish hotel with unique design elements and modern amenities.',
      rating: 4.8,
      address: '90 Cable Street, Te Aro, Wellington 6011, New Zealand',
      opening_hours: '',
      link: 'https://www.qthotels.com/wellington/',
      price_range: '200-400',
    },
    {
      name: 'InterContinental Wellington',
      city_name: 'Wellington',
      category: 'hotel',
      description:
        'Stay in sophistication at InterContinental Wellington, a luxury hotel located in the heart of the city.',
      rating: 4.7,
      address: '2 Grey Street, Wellington 6011, New Zealand',
      opening_hours: '',
      link: 'https://wellington.intercontinental.com/',
      price_range: '150-300',
    },
    {
      name: 'Rydges Wellington',
      city_name: 'Wellington',
      category: 'hotel',
      description:
        'Enjoy comfort and convenience at Rydges Wellington, a modern hotel with spacious rooms and city views.',
      rating: 4.7,
      address: '75 Featherston Street, Wellington 6142, New Zealand',
      opening_hours: '',
      link: 'https://www.rydges.com/accommodation/new-zealand/wellington/',
      price_range: '100-200',
    },
    {
      name: 'Bolton Hotel',
      city_name: 'Wellington',
      category: 'hotel',
      description:
        'Experience contemporary luxury at Bolton Hotel, offering stylish accommodations near the Beehive and Parliament.',
      rating: 4.6,
      address: '12 Bolton Street, Wellington 6011, New Zealand',
      opening_hours: '',
      link: 'https://www.boltonhotel.co.nz/',
      price_range: '150-300',
    },
    {
      name: 'Ohtel',
      city_name: 'Wellington',
      category: 'hotel',
      description:
        'Stay in boutique luxury at Ohtel, a waterfront hotel with unique decor and personalized service.',
      rating: 4.8,
      address: '66 Oriental Parade, Oriental Bay, Wellington 6011, New Zealand',
      opening_hours: '',
      link: 'https://www.ohtel.com/',
      price_range: '200-400',
    },
  ])
}
